<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-67LAP0I" failures="1" tests="6" name="Test Runner 2" time="0.104" errors="0" timestamp="2024-08-28T16:17:44 IST">
  <testcase classname="DistributedParallel.Test5" name="demo1" time="0.013">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at DistributedParallel.Test5.demo1(Test5.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- demo1 -->
  <testcase classname="DistributedParallel.Test5" name="demo2" time="0.001"/>
  <testcase classname="DistributedParallel.Test4" name="demo1" time="0.001"/>
  <testcase classname="DistributedParallel.Test4" name="demo2" time="0.002"/>
  <testcase classname="DistributedParallel.Test6" name="demo1" time="0.002"/>
  <testcase classname="DistributedParallel.Test6" name="demo2" time="0.002"/>
</testsuite> <!-- Test Runner 2 -->
